#define DEFAULT_WIFI_SSID "TEST"
#define DEFAULT_WIFI_PASSWORD "12345678"

#define UNDEF_PIN -1
#define GPIO_PIN_BUTTON 0
#define GPIO_PIN_BUTTON2 UNDEF_PIN

#define STM32_FRIMWARE_PATH ("/stm32ota/ota.bin")